services:
  backend:
    build:
      context: .
      dockerfile: DockerFile.backend
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/flights
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: DevPass03

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: DevPass03
      MYSQL_DATABASE: flights
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: ./src/frontend
      dockerfile: DockerFile.frontend
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      - backend

volumes:
  db_data:
