spring:
  application:
    name: FlightTicketApplication
  datasource:
    url: jdbc:mysql://localhost:3306/flights?createDatabaseIfNotExist=true
    username: root
    password: DevPass03
  flyway:
    schemas: flights
  jpa:
    show-sql: true